Fix typo
cake-contrib/Cake_Git pull request #113
Opened 2019-10-01 21:34 UTC by x-jokay

Fix typo.

2019-10-02 06:11 UTC, gep13 requested changes

2019-10-02 06:11 UTC, gep13 commented on README.md
> +```csharp
@x-jokay is there a reason that this was changed?  To the best of my knowledge, `cake` is a supported language type on GitHub.  Perhaps @devlead can confirm.

2019-10-02 06:36 UTC, devlead commented on README.md
> +```csharp
Yes `cake` is an supported GH flavored markdown code fence language
![image](https://user-images.githubusercontent.com/1647294/66022905-b23a6980-e4ef-11e9-9bfd-18e7302d489c.png)

2019-10-02 07:07 UTC, x-jokay commented on README.md
> +```csharp
Good to know :)

2019-10-02 07:14 UTC, x-jokay commented
@gep13 ready for review.

2019-10-02 07:20 UTC, gep13 approved these changes
LGTM!

2020-01-23 19:44 UTC, pascalberger approved these changes

2020-01-23 19:44 UTC, merged

2020-01-23 20:11 UTC, pascalberger commented
@x-jokay your changes have been merged, thanks for your contribution 👍