Update to LibGit2Sharp 0.26.2
cake-contrib/Cake_Git pull request #115
Opened 2020-01-23 13:49 UTC by soroshsabz

ITNOA

I have many error on Cake.Git on [AppVeyor build project](https://ci.appveyor.com/project/soroshsabz/commons/builds/30309097) so I update LibGit2Shart to 0.26.2

2020-01-23 16:04 UTC, soroshsabz commented
@x-jokay why we got many errors in test.cake ?

2020-01-23 16:14 UTC, x-jokay commented
@soroshsabz you can see the results of the builds [here](https://ci.appveyor.com/project/cakecontrib/cake-git/builds/30309483) and [here](https://travis-ci.org/cake-contrib/Cake_Git/builds/640905930).

This may be a problem due to [this](https://github.com/cake-contrib/Cake_Git/pull/115/files#diff-64308e660d481d0a88bcdcb115324f44L20) change.

2020-01-23 16:46 UTC, soroshsabz commented
@x-jokay Thanks for replaying, I fixed this issue, and now all CI is green :)

2020-01-23 19:55 UTC, pascalberger requested changes
@soroshsabz Thank you for the pull request. I added two comments which should be fixed before this can be merged.

2020-01-23 19:55 UTC, pascalberger commented on src/Cake.Git/Cake.Git.csproj
> +    <PackageReference Include="Cake.Core" Version="0.36.0" PrivateAssets="All" />
There's no reason to build against a newer version of Cake. Cake 0.33.0 is the earliest version with API compatibility and should be built against for maximum compatibility

2020-01-23 19:55 UTC, pascalberger commented on tools/packages.config
> +	<package id="Cake" version="0.36.0" />
Building with a newer version of Cake is unrelated to bumping LibGit2Sharp. Please remove it from this PR.

2020-01-24 00:39 UTC, soroshsabz commented
@pascalberger I downgrade Cake.Core , and I don't know why AppVeyor failed

2020-01-24 05:33 UTC, x-jokay commented
@soroshsabz your last [commit](https://github.com/cake-contrib/Cake_Git/pull/115/commits/5d40fd2a44a8c62d91d708bb9007f746a48b7e85) is not necessary, just revert it and squash the remainig first 1-4 commits to one commit, so only the `version number` change in `Cake.Git.csproj` for `LibGit2Sharp` and `LibGit2Sharp.NativeBinaries` will remain in 1 commit.

2020-01-24 11:34 UTC, soroshsabz commented
@x-jokay Ok I revert it and make one commit for change, please review it :)

2020-01-24 18:25 UTC, pascalberger approved these changes
LGTM

2020-01-24 18:25 UTC, merged

2020-01-24 18:26 UTC, pascalberger commented
@soroshsabz your changes have been merged, thanks for your contribution 👍