GH-127: Modify do/while in GitFindRootFromPath to avoid infinite loop
cake-contrib/Cake_Git pull request #128
Opened 2020-11-22 21:27 UTC by kcamp

This change simply looks at the current iteration of `parentDir` and provides a graceful termination consistent with the path simply not existing.  

Using `System.IO.DirectoryInfo` seemed to be the most straightforward/deterministic approach here; if there's a preferred approach, please feel free to suggest something different.

2020-11-28 11:55 UTC, pascalberger requested changes, later dismissed
@kcamp Thanks for fixing this 👍 

Code LGTM. Would it be possible for you to also add a test case testing the reported issue?

2020-11-28 12:48 UTC, kcamp commented
@pascalberger No problem, got those added.  Let me know if there's anything else you'd like.

2020-11-28 13:03 UTC, kcamp commented
Looking into the test failures on the latest push.  I _think_ it's going to wind up being environmental on the Travis builds.

2020-11-28 13:25 UTC, kcamp commented
@pascalberger I'm at a bit of a loss for how to address this.  In the latest Travis [OSX job ](https://travis-ci.org/github/cake-contrib/Cake_Git/jobs/746420358) we get the following:

```
========================================
Git-Find-Root-From-Path-TempDirectory
========================================
Attempting to resolve Git root directory from temp directory '/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/'...
...
Error: One or more errors occurred.
	Path at '/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/' should not be a valid Git repository.  Found Git root at '.'.
``` 

To me, this _seems_ unexpected (in terms of finding a valid git repository at that path), but I am not familiar with how Travis is configured.  The behavior definitely seems to indicate that `Repository.IsValid(".")` is evaluating `true` for that path and the loop is being broken gracefully without necessarily invoking the fix applied here.

Does this simply become a matter of scoping this new test to the `Local-Tests` task chain?  I added it to both `Default-Tests` and `Local-Tests` for good measure.  I patterned it after the `Git-IsValidRepository-TempDirectory` tests, so if we need to make it a bit more deterministic, I can start digging in on that in the next few days.

Ideas or advice on how to proceed?  Thanks! 👍

2021-06-05 19:09 UTC, nils-a commented
@kcamp Thanks for your contribution. As far as I can see, the build fails because the fix you implemented does not work on non-windows systems.

The main problem seems to be the line `var parentDir = fsPath.Combine("../").Collapse();` which on non-windows systems produces `.` as parent for `/tmp`. (And it will produce `C:\` as parent for `C:\` - which explains the infinite loop you observed.)

I have put up a solution that could be used to solve this at https://github.com/cake-build/cake/discussions/3387#discussioncomment-829716

Are you in a position to rebase this PR and implement a more general solution?

2021-06-06 13:38 UTC, kcamp commented
@nils-a  Yes, I can rework based on what you've commented.  Thanks for the feedback 👍

2021-12-12 22:40 UTC, devlead approved these changes

2021-12-12 22:42 UTC, devlead commented
@nils-a looks good to me, just need a rebase.

2021-12-13 01:08 UTC, augustoproiete approved these changes
LGTM

2021-12-13 01:08 UTC, augustoproiete commented on src/Cake.Git/GitAliases.Repository.cs
> +                }
```suggestion
                if (context.Environment.Platform.Family == PlatformFamily.Windows)
                {
                    // no more parents
                    return null;
                }
```

nitpick / C# brackets police :customs:

2021-12-13 01:08 UTC, augustoproiete commented on src/Cake.Git/GitAliases.Repository.cs
> +            }
```suggestion
            if(path.Segments.Length == 0)
            {
                return null;
            }
```

nitpick / C# brackets police :customs:

2021-12-13 07:40 UTC, nils-a commented on src/Cake.Git/GitAliases.Repository.cs
> +            }
Thanks! 👍 
I wonder why Rider did not pick that up, though.

2021-12-13 08:34 UTC, merged

2021-12-13 08:35 UTC, nils-a commented
@kcamp your changes have been merged, thanks for your contribution :+1: