Add support for annotated tags.
cake-contrib/Cake_Git pull request #32
Opened 2017-03-06 14:36 UTC by mbeelman

It should be helpfull if annotated tags are also supported.

2017-03-06 15:13 UTC, devlead requested changes
LGTM 👍 , could you please add tests in [test.cake](https://github.com/WCOMAB/Cake_Git/blob/master/test.cake) and I'll do a final review.

2017-05-29 12:24 UTC, pascalberger requested changes

2017-05-29 12:24 UTC, pascalberger commented on src/Cake.Git/GitAliases.Tag.cs
> +            if (tagName == null)
Should also check for empty string or string only containing whitespace since these are not valid tag names

2017-05-29 12:24 UTC, pascalberger commented on src/Cake.Git/GitAliases.Tag.cs
> +            if (name == null)
Should also check for empty string, since otherwise the [Signature Ctor](https://github.com/libgit2/libgit2sharp/blob/3f9b415fa1edfc31ce1ec2b4b3d18441c34adfff/LibGit2Sharp/Signature.cs#L35) would throw

2017-05-29 12:24 UTC, pascalberger commented on src/Cake.Git/GitAliases.Tag.cs
> +            if (email == null)
Should also check for empty string, since otherwise the [Signature Ctor](https://github.com/libgit2/libgit2sharp/blob/3f9b415fa1edfc31ce1ec2b4b3d18441c34adfff/LibGit2Sharp/Signature.cs#L35) would throw

2018-03-13 07:49 UTC, devlead approved these changes

2018-03-13 07:50 UTC, merged

2018-03-13 07:50 UTC, devlead commented
@mbeelman your changes have been merged, thanks for your contribution 👍