Added support for listing commits since a tag
cake-contrib/Cake_Git pull request #86
Opened 2018-12-17 11:11 UTC by mariusGundersen

This fixes #85.

2019-01-09 11:35 UTC, mariusGundersen commented
@devlead, any chance you have time to look into this? Or if you are busy, can you delegate the work to someone else? It would be very useful for us to get this fixed

2019-01-11 20:26 UTC, megakid commented
I would very much like this feature too!

2020-01-23 22:24 UTC, pascalberger commented
@mariusGundersen Thanks for the pull request. To be able to merge it, it needs to be rebased on current `develop` branch. Can you please rebase or allow edits from maintainers on your branch (see [documentation](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)) in which case I would be able to do the rebase myself.

2020-01-23 22:34 UTC, pascalberger requested changes

2020-01-23 22:34 UTC, pascalberger commented on src/Cake.Git/GitAliases.Log.cs
> +        ///     var result = GitLog("c:/temp/cake", "since tag");
Should be `GitLogTag`

2020-01-23 22:34 UTC, pascalberger commented on src/Cake.Git/GitAliases.Log.cs
> +        /// <returns>The path to the created repository.</returns>
Should be `<returns>Commits since the tag passed with <paramref name="sinceTag"/></returns>`

2020-01-24 07:29 UTC, mariusGundersen commented
@johnkors can you look into this? I think it would be useful for your build scripts.

2020-01-24 09:29 UTC, johnkors commented
@mariusGundersen  Could you allow the maintainers here to edit your branch in your fork, like @pascalberger  said? Seems as he's willing to take it on..?

2020-01-24 09:30 UTC, johnkors commented
Ah, sorry. I see, the fork is in _our_ org. Ok, I'll see what I can do!

2020-01-24 09:40 UTC, johnkors commented
Looks like I cannot set the checkbox of "let maintainers modify PR" flag, since I was not the author of the PR, so I rebased it.

2020-01-24 09:43 UTC, johnkors commented on src/Cake.Git/GitAliases.Log.cs
> +        ///     var result = GitLog("c:/temp/cake", "since tag");
✅ Updated in the rebase

2020-01-24 09:44 UTC, johnkors commented on src/Cake.Git/GitAliases.Log.cs
> +        /// <returns>The path to the created repository.</returns>
✅ Updated in the rebase

2020-01-24 10:27 UTC, pascalberger requested changes
@johnkors Thanks for the rebase 👍. 

One last thing: The test currently just outputs the result. It would be nice to have an actual test which breaks if another result than the expected is returned.

2020-01-24 10:27 UTC, pascalberger commented on test.cake
> +    Information("{0}", string.Join("\r\n", commit));
Can you change the test so that it actually breaks (throws an exception) if the returned values don't match the expected values.

2020-01-24 11:29 UTC, johnkors commented on test.cake
> +    Information("{0}", string.Join("\r\n", commit));
✅ Added validation here https://github.com/cake-contrib/Cake_Git/pull/86/files#diff-fbdef9605bcbb2541e6b786e3666969bR811

2020-01-24 18:06 UTC, pascalberger approved these changes
LGTM

2020-01-24 18:06 UTC, merged

2020-01-24 18:08 UTC, pascalberger commented
@mariusGundersen @johnkors  your changes have been merged, thanks for your contribution 👍

2020-02-03 09:44 UTC, johnkors commented
No rush, just wondering: any plans for releasing to nuget.org any time soon..?