Add return value to CreateBranch alias to avoid unnecessary rounds
cake-contrib/Cake_Git pull request #92
Opened 2019-02-11 14:55 UTC by Alea81

2019-04-17 17:44 UTC, christianbumann requested changes

2019-04-17 17:44 UTC, christianbumann commented on test.cake
> +		throw new Exception($"Result mismatch!");
Indentation wrong

2019-04-25 07:40 UTC, pascalberger approved these changes
LGTM

2019-04-25 08:15 UTC, merged

2019-04-25 08:15 UTC, pascalberger commented
@Alea81 your changes have been merged, thanks for your contribution 👍

You should delete and recreate your fork as I needed to rebase your `master` branch.